// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRfH_JlD51ZojA5i3-OqZTJLhFWVy7LM',
    appId: '1:786121748823:web:5c1b05820c7042808b8e12',
    messagingSenderId: '786121748823',
    projectId: 'ecowatt-6f949',
    authDomain: 'ecowatt-6f949.firebaseapp.com',
    storageBucket: 'ecowatt-6f949.firebasestorage.app',
    measurementId: 'G-HQLMP67XVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsYFGSP2Zg09_1cnf8HSfzv150-Fm4ZVc',
    appId: '1:786121748823:android:74222dfc2345391f8b8e12',
    messagingSenderId: '786121748823',
    projectId: 'ecowatt-6f949',
    storageBucket: 'ecowatt-6f949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCez00sl869ZF7uFMYhpYkGd5uGdzv0U9c',
    appId: '1:786121748823:ios:98ebdb06c33c2f1a8b8e12',
    messagingSenderId: '786121748823',
    projectId: 'ecowatt-6f949',
    storageBucket: 'ecowatt-6f949.firebasestorage.app',
    iosBundleId: 'com.example.ecowattmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCez00sl869ZF7uFMYhpYkGd5uGdzv0U9c',
    appId: '1:786121748823:ios:98ebdb06c33c2f1a8b8e12',
    messagingSenderId: '786121748823',
    projectId: 'ecowatt-6f949',
    storageBucket: 'ecowatt-6f949.firebasestorage.app',
    iosBundleId: 'com.example.ecowattmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeRfH_JlD51ZojA5i3-OqZTJLhFWVy7LM',
    appId: '1:786121748823:web:c460284790dd2bcf8b8e12',
    messagingSenderId: '786121748823',
    projectId: 'ecowatt-6f949',
    authDomain: 'ecowatt-6f949.firebaseapp.com',
    storageBucket: 'ecowatt-6f949.firebasestorage.app',
    measurementId: 'G-4KJKPZ0D4Q',
  );
}
